ALTER TABLE "User"
ADD COLUMN "isPlatformAdmin" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Club"
ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "aiEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "marketplaceEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "socialEnabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "billingPlan" TEXT NOT NULL DEFAULT 'FREE';
